name: Proto Compilation Check

on:
  push:
    paths:
      - '**.proto'
  pull_request:
    paths:
      - '**.proto'

jobs:
  check-proto:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Protobuf Compiler
      run: |
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler
    
    - name: Check protoc version
      run: protoc --version
    
    - name: Make sure the protobufs are valid
      run: ./build.sh